// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package ovirtapi

import (
	"encoding/json"
	"reflect"
)

func (api *API) GetVM(id string) (*VM, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(VM{}).Name()+"s", id)
	if err != nil {
		return nil, err
	}
	object := api.NewVM()
	err = json.Unmarshal(body, object)
	if err != nil {
		return nil, err
	}
	return object, err
}

func (api *API) GetAllVMs() ([]*VM, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(VM{}).Name()+"s", "")
	if err != nil {
		return nil, err
	}
	objects := []*VM{}
	err = json.Unmarshal(body, &struct {
		VM *[]*VM
	}{&objects})
	if err != nil {
		return nil, err
	}
	for _, object := range objects {
		object.Api = api
	}
	return objects, err
}

func (api *API) NewVM() *VM {
	return &VM{OvirtObject: OvirtObject{Api: api}}
}

func (object *VM) Save() error {
	body, err := json.MarshalIndent(object, "", "    ")
	if err != nil {
		return err
	}
	// If there is a link, it is an already saved object, we need to update it
	if object.OvirtObject.Href != "" {
		body, err = object.Api.Request("PUT", object.Api.ResolveLink(object.Href), body)
		if err != nil {
			return err
		}
	} else {
		link, err := object.Api.GetLink(reflect.TypeOf(VM{}).Name() + "s")
		if err != nil {
			return err
		}
		body, err = object.Api.Request("POST", link, body)
		if err != nil {
			return err
		}
	}
	tempObject := VM{OvirtObject: OvirtObject{Api: object.Api}}
	err = json.Unmarshal(body, &tempObject)
	*object = tempObject
	if err != nil {
		return err
	}
	return nil
}

func (api *API) GetCluster(id string) (*Cluster, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(Cluster{}).Name()+"s", id)
	if err != nil {
		return nil, err
	}
	object := api.NewCluster()
	err = json.Unmarshal(body, object)
	if err != nil {
		return nil, err
	}
	return object, err
}

func (api *API) GetAllClusters() ([]*Cluster, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(Cluster{}).Name()+"s", "")
	if err != nil {
		return nil, err
	}
	objects := []*Cluster{}
	err = json.Unmarshal(body, &struct {
		Cluster *[]*Cluster
	}{&objects})
	if err != nil {
		return nil, err
	}
	for _, object := range objects {
		object.Api = api
	}
	return objects, err
}

func (api *API) NewCluster() *Cluster {
	return &Cluster{OvirtObject: OvirtObject{Api: api}}
}

func (object *Cluster) Save() error {
	body, err := json.MarshalIndent(object, "", "    ")
	if err != nil {
		return err
	}
	// If there is a link, it is an already saved object, we need to update it
	if object.OvirtObject.Href != "" {
		body, err = object.Api.Request("PUT", object.Api.ResolveLink(object.Href), body)
		if err != nil {
			return err
		}
	} else {
		link, err := object.Api.GetLink(reflect.TypeOf(Cluster{}).Name() + "s")
		if err != nil {
			return err
		}
		body, err = object.Api.Request("POST", link, body)
		if err != nil {
			return err
		}
	}
	tempObject := Cluster{OvirtObject: OvirtObject{Api: object.Api}}
	err = json.Unmarshal(body, &tempObject)
	*object = tempObject
	if err != nil {
		return err
	}
	return nil
}

func (api *API) GetDataCenter(id string) (*DataCenter, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(DataCenter{}).Name()+"s", id)
	if err != nil {
		return nil, err
	}
	object := api.NewDataCenter()
	err = json.Unmarshal(body, object)
	if err != nil {
		return nil, err
	}
	return object, err
}

func (api *API) GetAllDataCenters() ([]*DataCenter, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(DataCenter{}).Name()+"s", "")
	if err != nil {
		return nil, err
	}
	objects := []*DataCenter{}
	err = json.Unmarshal(body, &struct {
		DataCenter *[]*DataCenter
	}{&objects})
	if err != nil {
		return nil, err
	}
	for _, object := range objects {
		object.Api = api
	}
	return objects, err
}

func (api *API) NewDataCenter() *DataCenter {
	return &DataCenter{OvirtObject: OvirtObject{Api: api}}
}

func (object *DataCenter) Save() error {
	body, err := json.MarshalIndent(object, "", "    ")
	if err != nil {
		return err
	}
	// If there is a link, it is an already saved object, we need to update it
	if object.OvirtObject.Href != "" {
		body, err = object.Api.Request("PUT", object.Api.ResolveLink(object.Href), body)
		if err != nil {
			return err
		}
	} else {
		link, err := object.Api.GetLink(reflect.TypeOf(DataCenter{}).Name() + "s")
		if err != nil {
			return err
		}
		body, err = object.Api.Request("POST", link, body)
		if err != nil {
			return err
		}
	}
	tempObject := DataCenter{OvirtObject: OvirtObject{Api: object.Api}}
	err = json.Unmarshal(body, &tempObject)
	*object = tempObject
	if err != nil {
		return err
	}
	return nil
}

func (api *API) GetTemplate(id string) (*Template, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(Template{}).Name()+"s", id)
	if err != nil {
		return nil, err
	}
	object := api.NewTemplate()
	err = json.Unmarshal(body, object)
	if err != nil {
		return nil, err
	}
	return object, err
}

func (api *API) GetAllTemplates() ([]*Template, error) {
	body, err := api.GetLinkBody(reflect.TypeOf(Template{}).Name()+"s", "")
	if err != nil {
		return nil, err
	}
	objects := []*Template{}
	err = json.Unmarshal(body, &struct {
		Template *[]*Template
	}{&objects})
	if err != nil {
		return nil, err
	}
	for _, object := range objects {
		object.Api = api
	}
	return objects, err
}

func (api *API) NewTemplate() *Template {
	return &Template{OvirtObject: OvirtObject{Api: api}}
}

func (object *Template) Save() error {
	body, err := json.MarshalIndent(object, "", "    ")
	if err != nil {
		return err
	}
	// If there is a link, it is an already saved object, we need to update it
	if object.OvirtObject.Href != "" {
		body, err = object.Api.Request("PUT", object.Api.ResolveLink(object.Href), body)
		if err != nil {
			return err
		}
	} else {
		link, err := object.Api.GetLink(reflect.TypeOf(Template{}).Name() + "s")
		if err != nil {
			return err
		}
		body, err = object.Api.Request("POST", link, body)
		if err != nil {
			return err
		}
	}
	tempObject := Template{OvirtObject: OvirtObject{Api: object.Api}}
	err = json.Unmarshal(body, &tempObject)
	*object = tempObject
	if err != nil {
		return err
	}
	return nil
}
